apiVersion: skaffold/v1beta9
kind: Config
build:
  artifacts:
    - image: gcr.io/bookshelf-ta/bookshelf
deploy:
  kubectl:
    manifests:
      - k8s-manifests/dev/*
      - k8s-manifests/config-map.yaml
profiles:
  - name: dev
    build:
      artifacts:
        - image: gcr.io/bookshelf-ta/bookshelf
          context: .
          sync:
            '**/*.js': .
    deploy:
      kubectl:
        manifests:
          - k8s-manifests/dev/*
          - k8s-manifests/config-map.yaml
  - name: qa
    build:
      artifacts:
        - image: gcr.io/bookshelf-ta/bookshelf
          context: .
          sync:
            '**/*.js': .
      googleCloudBuild:
        projectId: bookshelf-ta
    deploy:
      kubectl:
        manifests:
          - k8s-manifests/qa/*
          - k8s-manifests/config-map.yaml
    